project_id = "nchfxozhbtusjhhvjgdr"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.create-order]
verify_jwt = false

[functions.create-remita-payment]
verify_jwt = false

[functions.verify-remita-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false